"""Template conformance validator for AAS submodels.

Loads the Python classes generated by aas-submodel-to-py (one per IDTA
submodel template) and uses them to validate that a submodel instance
conforms to its declared template — beyond what the basyx-python-sdk
structural check already covers.

Lookup path:
  semanticId  →  template name (from index.json)
                  →  generated/{safe_name}.py
                      →  Submodel subclass inside that module
                          →  try instantiation with agent-supplied elements

If instantiation succeeds the submodel is template-conformant.
If it raises, the error message is returned to the agent for self-correction.
Templates without a generated class fall back silently (metamodel-only
validation still applies).
"""

import importlib.util
import inspect
import io
import json
import logging
import os
import re
import sys
import copy
from pathlib import Path
from typing import Optional

from basyx.aas.model import DictObjectStore, Submodel

log = logging.getLogger(__name__)

TEMPLATES_DIR = Path(os.environ.get("TEMPLATES_DIR", "/data/templates"))
_GENERATED_DIR = TEMPLATES_DIR / "generated"

# When true: put_submodel is rejected if the payload has no semanticId or if no
# validator class is registered for that semanticId.  Default off so existing
# deployments without registered templates are unaffected.
_require_val = os.environ.get("REQUIRE_TEMPLATE_VALIDATOR")
if _require_val is None:
    raise RuntimeError(
        "REQUIRE_TEMPLATE_VALIDATOR is not set. "
        "Add it to your .env file: true (reject submodels without a registered validator) "
        "or false (metamodel-only validation, permissive)."
    )
REQUIRE_TEMPLATE_VALIDATOR = _require_val.lower() == "true"

# semanticId → Submodel subclass, populated at first call to _registry().
_registry_cache: dict[str, type] | None = None


def _safe_name(name: str) -> str:
    """Reproduce the filename-safe transform used by submodel-templates-sync."""
    return re.sub(r'[<>:"/\\|?*]', "_", name)


def _find_submodel_class(module) -> type | None:
    """Return the first Submodel subclass found in a generated module."""
    for _, obj in inspect.getmembers(module, inspect.isclass):
        if issubclass(obj, Submodel) and obj is not Submodel and obj.__module__ == module.__name__:
            return obj
    return None


def _load_generated_module(py_path: Path) -> object | None:
    """Dynamically import a generated .py file as a module."""
    module_name = f"_aas_generated.{py_path.stem}"
    try:
        spec = importlib.util.spec_from_file_location(module_name, py_path)
        if spec is None or spec.loader is None:
            return None
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        return module
    except Exception as exc:
        log.debug("Could not load generated module %s: %s", py_path.name, exc)
        return None


def _build_registry() -> dict[str, type]:
    """Build the semanticId → TemplateClass lookup from index.json + generated/*.py."""
    registry: dict[str, type] = {}

    index_path = TEMPLATES_DIR / "index.json"
    if not index_path.exists():
        log.warning("Template index not found at %s — conformance validation disabled", index_path)
        return registry

    if not _GENERATED_DIR.exists():
        log.warning("Generated classes directory %s missing — conformance validation disabled", _GENERATED_DIR)
        return registry

    index: list[dict] = json.loads(index_path.read_text(encoding="utf-8"))

    for entry in index:
        name = entry.get("name", "")
        semantic_id = entry.get("semanticId", "").strip()
        if not name or not semantic_id:
            continue

        py_path = _GENERATED_DIR / f"{_safe_name(name)}.py"
        if not py_path.exists():
            continue

        module = _load_generated_module(py_path)
        if module is None:
            continue

        cls = _find_submodel_class(module)
        if cls is None:
            log.debug("No Submodel subclass found in %s", py_path.name)
            continue

        registry[semantic_id] = cls
        log.debug("Registered template class %s for semanticId %s", cls.__name__, semantic_id)

    log.info("Template conformance registry built: %d classes loaded", len(registry))
    return registry


def _registry() -> dict[str, type]:
    """Return the registry, building it once on first access."""
    global _registry_cache
    if _registry_cache is None:
        _registry_cache = _build_registry()
    return _registry_cache


def _extract_semantic_id(submodel_obj: Submodel) -> str | None:
    """Extract the plain string semanticId from a basyx Submodel object."""
    if submodel_obj.semantic_id is None:
        return None
    keys = list(submodel_obj.semantic_id.key)
    if not keys:
        return None
    return keys[0].value


def validate_conformance(submodel_obj: Submodel) -> Optional[str]:
    """Check template conformance of an already-SDK-validated Submodel object.

    Returns None on success (or when no template class exists for the
    semanticId).  Returns an error string on conformance failure — suitable
    for returning directly to the agent.
    """
    semantic_id = _extract_semantic_id(submodel_obj)
    if not semantic_id:
        if REQUIRE_TEMPLATE_VALIDATOR:
            return (
                "Submodel is missing a semanticId. "
                "Add a 'semanticId' field with the IDTA template URI for this submodel type "
                "(e.g. from get_template() or get_templates_index())."
            )
        return None

    cls = _registry().get(semantic_id)
    if cls is None:
        if REQUIRE_TEMPLATE_VALIDATOR:
            supported = sorted(_registry().keys())
            supported_str = ", ".join(supported) if supported else "(none loaded yet)"
            return (
                f"No validator registered for semanticId '{semantic_id}'. "
                f"Supported semanticIds: {supported_str}. "
                "Use get_templates_index() to find the correct semanticId for this submodel type."
            )
        log.debug("No template class for semanticId %s — skipping conformance check", semantic_id)
        return None

    # Build kwarg dict from the submodel's elements using the same naming
    # convention as the generator: lower_first(id_short), strip numeric endings.
    def _arg_name(id_short: str) -> str:
        s = id_short[0].lower() + id_short[1:] if id_short else id_short
        s = re.sub(r"_?\d+$", "", s)
        s = re.sub(r"\{\d+\}$", "", s)
        s = re.sub(r"__\d+__$", "", s)
        return s

    # Round-trip through JSON to detach parent links created during SDK parsing.
    # The generated template class expects fresh child objects.
    try:
        from basyx.aas.adapter.json import read_aas_json_file, write_aas_json_file

        buf = io.StringIO()
        write_aas_json_file(buf, DictObjectStore([copy.deepcopy(submodel_obj)]), stripped=False)
        fresh_store = read_aas_json_file(io.StringIO(buf.getvalue()), failsafe=False)
        fresh_submodel = next((o for o in fresh_store if isinstance(o, Submodel)), submodel_obj)
    except Exception as exc:
        log.debug("Could not round-trip submodel %s for template validation: %s", semantic_id, exc)
        fresh_submodel = submodel_obj

    element_kwargs = {_arg_name(e.id_short): copy.deepcopy(e) for e in fresh_submodel if e.id_short}

    try:
        cls(id_=fresh_submodel.id, **element_kwargs)
    except TypeError as exc:
        return f"Template conformance failed ({cls.__name__}): {exc}"
    except Exception as exc:
        if "Object has already a parent" in str(exc):
            log.warning(
                "Template class %s raised parent-ownership false positive for semanticId %s; accepting",
                cls.__name__,
                semantic_id,
            )
            return None
        return f"Template conformance failed ({cls.__name__}): {exc}"

    return None
